### ISSUE TITLE
公选2016网站地址提交

### ISSUE THREAD

**Issue by waxdoll** [waxdoll/HTMLGraph#3]
![githubissuecomment](https://cloud.githubusercontent.com/assets/1499495/15982474/3424d20c-2fbb-11e6-9219-b05f0df6b84c.png)

在评论输入框中录入以下格式的文本提交自己网站的地址：

电子商务14-3班 张召浦 07992110
http://你的用户名.github.io

提交后，请确保链接能打开你的网站首页（文件名必须为 index.html），谢谢！

域名后面不要加文件名！

**Comment by KaiYie** [comment]
信电学院15-17班  邓凯   04151692
http://KaiYie.github.io/

**Comment by cumtxujiabin** [comment]
计算机学院 15-14班 徐嘉宾 08153533 ［http://cumtxujiabin.github.io］(http://cumtxujiabin.github.io)

**Comment by cumtxujiabin** [comment]
计算机学院 15-14班 徐嘉宾 08153533
[http://cumtxujiabin.github.io](http://cumtxujiabin.github.io)

**Comment by 13236032250** [comment]
信电学院14-3班 司进涛 04141511

**Comment by KaiYie** [comment]
你发错了吧！我是力建15级新生，并不认识你！

--
发自我的OPPO智能手机

13236032250 <notifications@github.com>编写：

**Comment by Cumtyuanfeng** [comment]
计算机学院 15级14班 袁峰 08153537
[http://cumtyuanfeng.github.io](http://cumtyuanfeng.github.io)

**Comment by hellojiabin** [comment]
计算机学院 15级14班 马志宁 08153528
[http://hellojiabin.github.io](http://hellojiabin.github.io)

**Comment by upzhujie** [comment]
计算机学院 15级13班 朱杰  08153508
http://beautytangqi.github.io

**Comment by sys1874** [comment]
网络工程13-2班 施云生 08133513
http://qq578417645.github.io

**Comment by wertyuim** [comment]
计算机学院 15级1班 李明灿 08153120
http://wertyuim.github.io

**Comment by LYQSIMTH** [comment]
外文学院   15级英语2班  梁昱琦   12154663
https://lyqsimth.github.io/

**Comment by Eonh1u** [comment]
计算机学院 15级12班 户玉拓 08153460
[https://huyutuo.github.io/](https://huyutuo.github.io/)

**Comment by cumthuayu** [comment]
计算机学院 15级13班 花宇 08153490
[https://cumthuayu.github.io/](https://cumthuayu.github.io/)

**Comment by waxdoll** [comment]
@cumthuayu @huyutuo @hellojiabin @Cumtyuanfeng @cumtxujiabin 最后一次课的时候说过了，不是不允许使用模版，但是页面必须是自己的内容，谢谢！

**Comment by waxdoll** [comment]
@13236032250 没有提供 github pages 网站地址

**Comment by mytail2** [comment]
计算机学院 15级 6班 孙靖凯 08153281
http://mytail2.github.io

**Comment by onepear** [comment]
艺术与设计学院 14级工业设计3班 李苗 08143195
http://onepear.github.io/

**Comment by qiuyanliang** [comment]
信电学院 15级17班 邱颜靓 04151704
http://qiuyanliang.github.io/

**Comment by qiuyanliang** [comment]
信电学院 15级17班 邱彦靓 04151704
http://qiuyanliang.github.io/
上一条字错了

**Comment by wangkang183** [comment]
艺术与设计学院 工业设计14-1 王康 15145093
http://wangkang183.github.io/

**Comment by guanzhentian** [comment]
计算机学院 14级2班  官圳填  08143097 
http://guanzhentian.github.io/
**核心是JavaScript代码**

**Comment by YuxiangM** [comment]
1

**Comment by cumtxzh** [comment]
机电学院   15级11班徐增辉  03151184
https://cumtxzh.github.io

**Comment by cumtxzh** [comment]
机电学院  15级11班  徐增辉 03151184
https://cumtxzh.github.io/

**Comment by ZHANGRUIzr** [comment]
理学院 15级物理4班 张锐 10154334
https://ZHANGRUIzr.github.io/

**Comment by Wangxiaohan-King** [comment]
信电学院 15级17班  王霄汉 04151707

https://xiaohan521.github.io/

**Comment by chdfq** [comment]
计算机学院 15级10班 朱玉峰 08153415
https://chdfq.github.io/

**Comment by cumtyangyi** [comment]
环境与测绘学院  15级环境01班  杨意  07152884 
https://cumtyangyi.github.io

**Comment by donchou** [comment]
环测学院  土地15-2班   周登继   07153069

**Comment by ghost** [comment]
环测学院 土地15-2班 周登继 07153069
https://donchou.github.io

**Comment by xzjcumt** [comment]
信电学院 15-10 肖子健 04151505
https://xzjcumt.github.io

**Comment by dengke0** [comment]
机电学院  15-10  徐登科 03151157
https://dengke0.github.io/ke/

**Comment by dengke0** [comment]
机电 15-10 徐登科 03151157
https://dengke0.github.io/ke/

**Comment by CZWatson** [comment]
文法 中语15-3  陈子薇 11154534
http://Emma-Watson.github.io

**Comment by haicker** [comment]
资源学院 15级1班 孙海川 05151792
haicker.github.io

**Comment by haicker** [comment]
资源学院 15级1班 孙海川 05151792
http://haicker.github.io

**Comment by wutongjiushi** [comment]
计算机学院 15级 10班 周玥 08153424
http://wutongjiushi.github.io

**Comment by 08153457** [comment]
计算机学院 15级 12班 陈翔 08153457
[计算机学院 15级 12班 陈翔 08153457.zip](https://github.com/waxdoll/HTMLGraph/files/344835/15.12.08153457.zip)

**Comment by liujinxiang** [comment]
环测学院 15级 七班 刘金香 07152826
https://liujinxiang.github.io

**Comment by guozhiyu** [comment]
计算机学院 14级计科1班 郭志宇 09143531
http://guozhiyu.github.io

**Comment by ZD61** [comment]
环测学院 15级 七班 张作栋 07152820
https://zd61.github.io
存在问题，外链的一个视频看不了，我的家乡板块滚动照片无法实现。。。
发现存在很多问题。。。
知道渣。。o(︶︿︶)o唉

**Comment by cypresss** [comment]
计算机学院 15级9班 韩柏茹 08153389
[https://seclediff.github.io/index.html](https://seclediff.github.io/index.html)

**Comment by huhuiqing** [comment]
环境与测绘学院 15级7班 胡卉清 07152824
https://github.com/huhuiqing/huhuiqing.io/

**Comment by YiLuo007** [comment]
理学院 物理15-3班 孙茂淞  10154296
https://yiluo007.github.io/

**Comment by luyunli** [comment]
环境与测绘学院 测绘类15-5班 洪聪颖 07152751
https://undersun-shadow.github.io/

**Comment by zh9** [comment]
老师你好！第一次看到有学生作业通过Github来提交的，不知道贵校叫什么，有点感兴趣！学生们做的网页很多都太简陋了。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。

**Comment by waxdoll** [comment]
@zh9 中国矿业大学，这是公共选修课，全校同学都可以选的，确实有些难为一些工科和文科的同学，主要目的是让他们拥有属于他们自己的可以互联网访问的网站。

**Comment by hxswen** [comment]
计算机15级3班  何昕松 08153180

https://hxswen.github.io/

**Comment by chan-shaw** [comment]
计算机 计14-6班 肖郴 08143327
https://jackcxiao.github.io

**Comment by shenjingxing** [comment]
材料学院 材料类14-3班 沈竞兴 06142252
https://shenjingxing.github.io/

**Comment by zhj2391304086** [comment]
信电学院15-3班 张宏杰 04151300
http://zhj2391304086.github.io

**Comment by findmysilence** [comment]
老师我上传永远上传失败啊，怎么办，能不能你发个qq或者邮箱我吧rar压缩文件发给你啊？

**Comment by findmysilence** [comment]
或者老师你点这个链接下载吧，如果不行的话，这是我的电话15325770477，老师谢谢了
https://pan.baidu.com/s/1pL3XWYv

**Comment by wuqiyang00** [comment]
计算机学院 15级7班 吴启洋 08153318

https://wuqiyang00.github.io/

**Comment by iamsail** [comment]
计算机学院 15级10班 李长航  08153398
http://iamsail.github.io/

**Comment by findmysilence** [comment]
计算机学院 15级 10班 何一凡 08153395
https://findmysilence.github.io/

**Comment by sjhAlexander** [comment]
电力学院  15级  1班    施佳皓  17155386
https://sjhalexander.github.io/

**Comment by zhangxin64** [comment]
地质类15-2班 张新 05151828
https://zhangxin64.github.io/

**Comment by wdfec** [comment]
cumtzzp@163.com

**Comment by wangkang183** [comment]
工业设计14-1班 王康15145093
wangkang183.github.io

**Comment by CZWatson** [comment]
11154534  陈子薇  文法学院15中三
czwatson.github.io

**Comment by cherishwatermelon** [comment]
计算机 计14 -4班 赵茜茜 08143188
https://cherishwatermelon.github.io

**Comment by WhenWillISeeYouAgain** [comment]
能源与动力15-1班 何世玉 17155377
https://whenwilliseeyouagain.github.io/

**Comment by xiaojinxj** [comment]
孙鑫  艺术学院工设14-2班  15145131
http://pan.baidu.com/s/1c5e4Lw
github总是失败

**Comment by newmsk** [comment]
卢加瑞 管理学院 电商3班 09153759
http://newmsk.github.io

**Comment by wang520yan** [comment]
王彦  计算机学院 计科14-4班  08143268
https://wang520yan.github.io

**Comment by buxihuan** [comment]
张雪颖   计算机学院     15-1班   08153143
https://buxihuan.github.io/

**Comment by Yxty** [comment]
宗碧 信电学院15-3班 04151304
https://Yxty.github.io/

**Comment by xieyujieerzi** [comment]
谢玉杰 信电学院15-17班 04151709
https://xieyujieerzi.github.io/

**Comment by baby-show** [comment]
郑秀 材料学院15-1班  14154835
https://baby-show.github.io/

**Comment by zhangaaa** [comment]
张蕊蕊 计算机学院15-3 08153207
https://zhangaa.github.io/

**Comment by zhangaaa** [comment]
王婧宇 计算机学院 15-3  08153205
https://hehwjy.github.io/

**Comment by wl2575** [comment]
信电15-6班 王乐 04151385
https://wl2575.github.io

**Comment by Caroline-cccat** [comment]
电力学院 能动15-5班 宋耀阳 17155524
http://pan.baidu.com/s/1c2cAjba 密码：0tng
github上传的时候总是出现failed to sync this branch. You might need to open a shell and debug the state of this repo.这个错误。。试了各种办法都解决不了。。我会再试试的，先提交个百度盘，麻烦老师了

**Comment by Emma14154830** [comment]
高晓纯  材料学院15-1班 14154830
https://emma14154830.github.io/

**Comment by hujunsen** [comment]
胡俊森 艺术与设计学院环境设计三班 15155107
https://hujunsen.github.io/

**Comment by songjiaweiwei** [comment]
宋佳蔚 艺术与设计学院环境设计三班 15155123
https://songjiaweiwei.github.io/

**Comment by javises** [comment]
李佳丽 艺术与设计学院环境设计二班 15155093
https://javises.github.io/

**Comment by ghost** [comment]
计算机学院 15级7班 肖德畅 08153319

https://codol.github.io/

**Comment by TibetanBlue** [comment]
王莎莎 材料学院15-5班 14154960
https://shasha97.github.io

**Comment by pitman121** [comment]
电信14-4班 郭国强 04141331、
https://pitman121.githup.io

**Comment by waxdoll** [comment]
**作业提交截止日期延长至 2016-07-14 00:00:00。**

**Comment by jekiki** [comment]
能化14-1班 张鹏程 06142583.
https://jekiki.github.io/
